[general]
import = [
    # autumn
    # afterglow
    # hatsunemiku
    # alacritty_0_12
    # ashes_dark
    # aura
    # ayu_mirage
    # base16_default_dark
    # gnome_terminal
    # hard_hacker
    # papercolor_light
    # github_light
    # chicago95
    # ganbaru_matcha
    # pastel_dark
    "~/.config/alacritty/themes/themes/pastel_dark.toml"
]

[window]
level = "AlwaysOnTop"
blur = true
decorations = "buttonless"
dynamic_padding = false
opacity = 1.0

[window.padding]
x = 15
y = 10

[window.dimensions]
columns = 85
lines = 25

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Underline", blinking = "On" }
unfocused_hollow = true
thickness = 0.15

[font]
size = 9.0

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"
